name: CI/CD Pipeline

# Déclencher le pipeline lors d'un push sur la branche main ou develop
on:
  push:
    branches:
      - main
      - develop

jobs:
  # Premier job: Builder l'image Docker
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }} /var/www/Junia-A5/Junia-5A/dockerfile/

  # Deuxième job: Pousser l'image sur Docker Hub (se lance après "build")
  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}

